import React, { useState } from 'react';
import { Search, Download, Bookmark, BookmarkCheck, FileText, ExternalLink, X } from 'lucide-react';
import { orbinexStore } from '../data/store';
import { ResearchArticle } from '../types';

export const SpaceResearchPage: React.FC = () => {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState<string>('ALL');
  const [activeArticle, setActiveArticle] = useState<ResearchArticle | null>(null);

  const categories = [
    'ALL',
    'Satellite Technology',
    'Space Science',
    'AI + Space',
    'Planetary Science',
    'Astronomy',
  ];

  const articles = orbinexStore.researchArticles.filter((art) => {
    const matchesSearch =
      art.title.toLowerCase().includes(search.toLowerCase()) ||
      art.author.toLowerCase().includes(search.toLowerCase()) ||
      art.summary.toLowerCase().includes(search.toLowerCase());
    const matchesCat = category === 'ALL' || art.category === category;
    return matchesSearch && matchesCat;
  });

  const handleDownload = (article: ResearchArticle) => {
    orbinexStore.incrementDownload(article.id);
    const element = document.createElement('a');
    const file = new Blob([
      `ORBINEX RESEARCH ARCHIVE // AMT INITIATIVE\n` +
      `TITLE: ${article.title}\n` +
      `AUTHOR: ${article.author} (${article.authorAffiliation})\n` +
      `CATEGORY: ${article.category}\n` +
      `DOI: ${article.doi || 'ORB-PREPRINT'}\n` +
      `DATE: ${article.date}\n\n` +
      `ABSTRACT:\n${article.fullAbstract}\n\n` +
      `KEYWORDS: ${article.tags.join(', ')}\n`
    ], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `${article.title.slice(0, 30).replace(/\s+/g, '_')}_ORBINEX.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12 space-y-12">
      {/* Header */}
      <div className="space-y-3">
        <div className="text-xs font-mono text-neutral-500 tracking-widest uppercase">
          PEER PUBLICATIONS // OPEN RESEARCH REPOSITORY
        </div>
        <h1 className="text-3xl sm:text-5xl font-bold font-display text-white">
          Space Science &amp; Technology Research
        </h1>
        <p className="text-xs sm:text-sm text-neutral-400 max-w-2xl leading-relaxed">
          Open access research papers, preprints, and hardware schematics generated by the ORBINEX research groups, collegiate contributors, and independent fellows.
        </p>
      </div>

      {/* Search and Filters */}
      <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4">
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 absolute left-3 top-3 text-neutral-500" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search papers, authors, topics (e.g. Swarm, SDR, Lunar)..."
            className="w-full bg-neutral-950 border border-neutral-800 rounded pl-9 pr-4 py-2 text-xs font-mono text-white placeholder-neutral-500 focus:outline-none focus:border-neutral-500"
          />
        </div>

        <div className="flex items-center gap-1.5 overflow-x-auto text-xs font-mono no-scrollbar">
          {categories.map((cat) => (
            <button
              key={cat}
              type="button"
              onClick={() => setCategory(cat)}
              className={`px-3 py-1.5 rounded transition-colors whitespace-nowrap cursor-pointer ${
                category === cat
                  ? 'bg-white text-black font-semibold'
                  : 'bg-neutral-950 text-neutral-400 border border-neutral-800 hover:text-white'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Research Articles Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {articles.map((art) => {
          const isSaved = orbinexStore.savedArticles.includes(art.id);
          return (
            <div
              key={art.id}
              className="p-6 bg-neutral-950 border border-neutral-900 hover:border-neutral-800 rounded space-y-4 flex flex-col justify-between transition-colors"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between text-[11px] font-mono text-neutral-500">
                  <span className="text-neutral-300 font-medium">{art.category}</span>
                  <span>{art.date}</span>
                </div>

                <h2
                  onClick={() => setActiveArticle(art)}
                  className="text-lg font-bold text-white font-display hover:text-neutral-300 transition-colors cursor-pointer leading-snug"
                >
                  {art.title}
                </h2>

                <div className="text-xs text-neutral-400 font-mono">
                  {art.author} · <span className="text-neutral-500">{art.authorAffiliation}</span>
                </div>

                <p className="text-xs text-neutral-400 leading-relaxed">
                  {art.summary}
                </p>

                <div className="flex flex-wrap gap-1.5 pt-1">
                  {art.tags.map((tag, idx) => (
                    <span
                      key={idx}
                      className="text-[10px] font-mono text-neutral-400 bg-neutral-900 border border-neutral-800 px-2 py-0.5 rounded"
                    >
                      #{tag}
                    </span>
                  ))}
                </div>
              </div>

              <div className="pt-4 border-t border-neutral-900 flex items-center justify-between text-xs font-mono">
                <button
                  type="button"
                  onClick={() => setActiveArticle(art)}
                  className="text-white hover:text-neutral-300 underline font-medium cursor-pointer"
                >
                  READ ABSTRACT →
                </button>

                <div className="flex items-center gap-3">
                  <button
                    type="button"
                    onClick={() => orbinexStore.toggleSaveArticle(art.id)}
                    className="text-neutral-400 hover:text-white transition-colors"
                    title={isSaved ? 'Remove from saved' : 'Save paper'}
                  >
                    {isSaved ? <BookmarkCheck className="w-4 h-4 text-emerald-400" /> : <Bookmark className="w-4 h-4" />}
                  </button>

                  <button
                    type="button"
                    onClick={() => handleDownload(art)}
                    className="text-neutral-400 hover:text-white flex items-center gap-1 transition-colors"
                    title="Download preprint"
                  >
                    <Download className="w-4 h-4" />
                    <span className="text-[11px] tabular-nums">{art.downloadsCount}</span>
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Article Detail Reader Modal */}
      {activeArticle && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm animate-fadeIn">
          <div className="w-full max-w-2xl bg-neutral-950 border border-neutral-800 rounded-lg p-6 sm:p-8 space-y-6 max-h-[85vh] overflow-y-auto">
            <div className="flex items-start justify-between gap-4 pb-4 border-b border-neutral-900">
              <div className="space-y-1">
                <div className="text-xs font-mono text-neutral-500 uppercase">{activeArticle.category}</div>
                <h3 className="text-2xl font-bold font-display text-white">{activeArticle.title}</h3>
                <div className="text-xs font-mono text-neutral-300">
                  {activeArticle.author} · {activeArticle.authorAffiliation}
                </div>
              </div>
              <button
                type="button"
                onClick={() => setActiveArticle(null)}
                className="p-1 text-neutral-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-2">
              <div className="text-xs font-mono text-neutral-500 uppercase">FULL SCIENTIFIC ABSTRACT</div>
              <p className="text-sm text-neutral-300 leading-relaxed font-sans">
                {activeArticle.fullAbstract}
              </p>
            </div>

            <div className="p-4 bg-neutral-900/50 border border-neutral-800 rounded font-mono text-xs space-y-2">
              <div>
                <span className="text-neutral-500">DIGITAL OBJECT IDENTIFIER: </span>
                <span className="text-white font-semibold">{activeArticle.doi || 'ORB-2026-PAPER'}</span>
              </div>
              <div>
                <span className="text-neutral-500">ARCHIVE CITATION: </span>
                <span className="text-neutral-300">
                  {activeArticle.author} ({activeArticle.date.slice(0, 4)}). {activeArticle.title}. ORBINEX Space Publications.
                </span>
              </div>
            </div>

            <div className="flex items-center justify-between pt-4 border-t border-neutral-900">
              <button
                type="button"
                onClick={() => handleDownload(activeArticle)}
                className="px-4 py-2 bg-white text-black font-mono text-xs font-semibold rounded hover:bg-neutral-200 transition-colors flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                <span>DOWNLOAD CITATION &amp; PREPRINT</span>
              </button>

              <button
                type="button"
                onClick={() => setActiveArticle(null)}
                className="px-4 py-2 bg-neutral-900 hover:bg-neutral-800 text-neutral-300 font-mono text-xs rounded border border-neutral-800"
              >
                CLOSE
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
